sonar.organization=dheyme
sonar.projectKey=Dheyme_meu-bolso-ci
sonar.projectName=meu-bolso-ci

sonar.sources=meu-bolso-api/src
sonar.tests=meu-bolso-api/src
sonar.test.inclusions=**/*.spec.ts
sonar.javascript.lcov.reportPaths=meu-bolso-api/coverage/lcov.info
