sonar.organization=dheyme
sonar.projectKey=Dheyme_meu-bolso-ci
sonar.projectName=meu-bolso-ci

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
