name: CI - Meu Bolso API

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
        working-directory: ./meu-bolso-api

      - name: Build first
        run: npm run build
        working-directory: ./meu-bolso-api

      - name: Run tests
        run: npm run test -- --passWithNoTests
        working-directory: ./meu-bolso-api

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: ./meu-bolso-api
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}